name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup
	uses: docker/setup-qemu-action@v2

      -
        name: buildx
	uses: docker/setup-buildx-action@v2

      - 
        name: login to docker
	uses: docker/login-action@v2
	with:
	  username: ${{ secrets.DOCKER_USER }}
	  password: ${{ secrets.DOCKER_PASSWORD }}
      -
       name: build and push
       uses: docker/build-push-action@v3
       with:
         push: true
	 tags: user/app:latest
       
